<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .p {
            font-family: "Arial Narrow";
            font-weight: bold;
            font-size: 540% ;
            color: darkcyan;
        }

    </style>
</head>
<body>
<?php
\Library\Session::setContent('REQUEST_URI', $_SERVER['REQUEST_URI']);
?>


<p class="p"><i>Тестовий сайт</i></p>
</body>
</html>