<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .p {
            font-family: "Arial Narrow";
            font-weight: bold;
            font-size: 540% ;
            color: darkcyan;
        }



        /* Базовые стили слоя затемнения и модального окна  */
        .overlay {
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            z-index: 10;
            display: none;
            /* фон затемнения */
            background-color: rgba(0, 0, 0, 0.65);
            position: fixed; /* фиксированное поцизионирование */
            cursor: default; /* тип курсара */
        }
        /* активируем слой затемнения */
        .overlay:target {
            display: block;
        }
        /* стили модального окна */
        .popup {
            top: -100%;
            right: 0;
            left: 50%;
            font-size: 14px;
            z-index: 20;
            margin: 0;
            width: 85%;
            min-width: 320px;
            max-width: 600px;
            /* фиксированное позиционирование, окно стабильно при прокрутке */
            position: fixed;
            padding: 15px;
            border: 1px solid #383838;
            background: #fefefe;
            /* скругление углов */
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            -ms-border-radius: 4px;
            border-radius: 4px;
            font: 14px/18px 'Tahoma', Arial, sans-serif;
            /* внешняя тень */
            -webkit-box-shadow: 0 15px 20px rgba(0,0,0,.22),0 19px 60px rgba(0,0,0,.3);
            -moz-box-shadow: 0 15px 20px rgba(0,0,0,.22),0 19px 60px rgba(0,0,0,.3);
            -ms-box-shadow: 0 15px 20px rgba(0,0,0,.22),0 19px 60px rgba(0,0,0,.3);
            box-shadow: 0 15px 20px rgba(0,0,0,.22),0 19px 60px rgba(0,0,0,.3);
            -webkit-transform: translate(-50%, -500%);
            -ms-transform: translate(-50%, -500%);
            -o-transform: translate(-50%, -500%);
            transform: translate(-50%, -500%);
            -webkit-transition: -webkit-transform 0.6s ease-out;
            -moz-transition: -moz-transform 0.6s ease-out;
            -o-transition: -o-transform 0.6s ease-out;
            transition: transform 0.6s ease-out;
        }
        /* активируем модальный блок */
        .overlay:target+.popup {
            -webkit-transform: translate(-50%, 0);
            -ms-transform: translate(-50%, 0);
            -o-transform: translate(-50%, 0);
            transform: translate(-50%, 0);
            top: 20%;
        }
        /* формируем кнопку закрытия */
        .close {
            top: -10px;
            right: -10px;
            width: 20px;
            height: 20px;
            position: absolute;
            padding: 0;
            border: 2px solid #ccc;
            -webkit-border-radius: 15px;
            -moz-border-radius: 15px;
            -ms-border-radius: 15px;
            -o-border-radius: 15px;
            border-radius: 15px;
            background-color: rgba(61, 61, 61, 0.8);
            -webkit-box-shadow: 0px 0px 10px #000;
            -moz-box-shadow: 0px 0px 10px #000;
            box-shadow: 0px 0px 10px #000;
            text-align: center;
            text-decoration: none;
            font: 13px/20px 'Tahoma', Arial, sans-serif;
            font-weight: bold;
            -webkit-transition: all ease .8s;
            -moz-transition: all ease .8s;
            -ms-transition: all ease .8s;
            -o-transition: all ease .8s;
            transition: all ease .8s;
        }
        .close:before {
            color: rgba(255, 255, 255, 0.9);
            content: "X";
            text-shadow: 0 -1px rgba(0, 0, 0, 0.9);
            font-size: 12px;
        }
        .close:hover {
            background-color: rgba(252, 20, 0, 0.8);
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
        }
        /* изображения внутри окна */
        .popup img {
            width: 100%;
            height: auto;
        }
        /* миниатюры слева/справа */
        .pic-left,
        .pic-right {
            width: 25%;
            height: auto;
        }
        .pic-left {
            float: left;
            margin: 5px 15px 5px 0;
        }
        .pic-right {
            float: right;
            margin: 5px 0 5px 15px;
        }
        /* элементы м-медиа, фреймы */
        .popup embed,
        .popup iframe {
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            display:block;
            margin: auto;
            min-width: 320px;
            max-width: 600px;
            width: 100%;
        }
        .popup h2 { /* заголовок 2 */
            margin: 0;
            color: #008000;
            padding: 5px 0px 10px;
            text-align: left;
            text-shadow: 1px 1px 3px #adadad;
            font-weight: 500;
            font-size: 1.4em;
            font-family: 'Tahoma', Arial, sans-serif;
            line-height: 1.3;
        }
        /* параграфы */
        .popup p {margin: 0; padding: 5px 0}
    </style>
</head>
<body>


<p class="p"><i>Тестовий сайт</i></p>
<!-- Ссылки на вызов модальных окон-->
<a href="#win1" class="button button-green">Открыть окно 1</a>
<a href="#win2" class="button button-red">Открыть окно 2</a>
<a href="#win3" class="button button-blue">Видео в окне 3</a>
<a href="#win4" class="button button-orange">Фото в окне 4</a>
<!-- Вызов окна через миниатюру изображения -->
<a href="#win5"><img title="" src="img/realism_lrg.jpg" width="150" height="150" alt="" /></a>
<!-- Модальное окно №1 -->
<a href="#x" class="overlay" id="win1"></a>
<div class="popup">
    Здесь вы можете разместить любое содержание, текст с картинками или видео!
    <a class="close"title="Закрыть" href="#close"></a>
</div>
<!-- Модальное окно №2 -->
<a href="#x" class="overlay" id="win2"></a>
<div class="popup">
    Здесь вы можете разместить любое содержание, текст с картинками или видео!
    <a class="close" title="Закрыть" href="#close"></a>
</div>
<!-- Модальное окно №3 -->
<a href="#x" class="overlay" id="win3"></a>
<div class="popup">
    <h2>Заголовок</h2>
    Здесь вставляете видео своё или с любого стороннего ресурса, YouTube, Vimeo и т.д.(iframe, embed)...
    <a class="close" title="Закрыть" href="page.html" onclick="return false"></a><!-- Выключение видео при закрытии окна -->
</div>
<!-- Модальное окно №4 -->
<a href="#x" class="overlay" id="win4"></a>
<div class="popup">
    <img class="is-image" src="ваша-картинка.jpg" alt="" />
    <a class="close" title="Закрыть" href="#close"></a>
</div>
<!-- Модальное окно №5 -->
<a href="#x" class="overlay" id="win5"></a>
<div class="popup">
    <img class="is-image" src="ваша-картинка.jpg" alt="" />
    <a class="close" title="Закрыть" href="#close"></a>
</div>
</body>
</html>