<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<br>
<h4><b>Форма для додавання книги до каталогу.</b></h4>
<br><br>
<form method="post">
    <label for="title">Назва книги</label>
    <br>
    <input type="text" name = "title" placeholder="">
    <br><br>
    <label for="price">Ціна книги</label>
    <br>
    <input type="number" name = "price" >
    <br><br>
    <label for="is_active">Наявність</label>
    <br>
    <input type="number" max="1" name = "is_active" >
    <br><br>
    <label for="description">Короткий зміст</label>
    <br>
    <textarea type="text" name = "description" cols="150" rows="15" ></textarea>
    <br><br>
    <input type="hidden" name="id">
    <button name="cancel" value="cancel">Сасувати</button>
    <button name="save" value="save">Додати книгу</button>
</form>

</body>
</html>