<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<br>
<br>
<br>
Книга № <?= $array_book['id']?>
<br>
<br>
Назва книги - "<?= $array_book['title']?>"
<br>
<br>
<br>
Oпис книги:
<br>
<br>
<?= $array_book['description'] ?>
<br>
<br>
<br>
<button onclick="location.href='index.php?route=book2/index&page=<?=$_GET['page'] ?>'">Повернутись до каталогу</button>
<br>
<br>
<br>


</body>
</html>