<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<b>Форма для редагування книги з каталогу.</b>
<br>

<form method="post">
    <br><br>
    <input type="hidden" name="id" value="<?= $array['id']?>">
    <label for="title">Назва книги</label>
    <br>
    <input type="text" name = "title" value = "<?= $array['title']?>" placeholder="">
    <br><br>
    <label for="price">Ціна книги</label>
    <br>
    <input type="number" name = "price" value = "<?= $array['price']?>">
    <br><br>
    <label for="is_active">Наявність</label>
    <br>
    <input type="number" max="1" name = "is_active" value = "<?= $array['is_active']?>">
    <br><br>
    <label for="description">Короткий зміст</label>
    <br>
    <textarea type="text" name = "description" cols="150" rows="15" ><?= $array['description']?></textarea>
    <br><br>
    <button name="no" value="index">Сасувати зміни</button>
    <button>Зберегти зміни</button>
</form>

</body>
</html>