<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    .bold {
        color: crimson;
        font-size: large;
        text-decoration: underline;
    }
    </style>
</head>
<body>

<form method="post">
    <button  formmethod="get" name="route" value="book/add"><b>Додати нову книгу до каталогу.</b></button>
</form>
<table border="3" width="100%">
    <tr>
        <th bgcolor="#87cefa" >Номер книги</th>
        <th bgcolor="#87cefa">Назва книги</th>
        <th bgcolor="#87cefa">Ціна</th>
        <th bgcolor="#87cefa">Наявність</th>
        <th bgcolor="#87cefa" align="сenter" colspan="2">Дії</th>

    </tr>

    <?php
    foreach ($array_book as $key => $value):
        ?>
        <tr>
            <td><?= $value['id'] ?></td>
            <td><a href="#" title="<?= $value['description'] ?>"><?= $value['title'] ?></a></td>
            <td><?= $value['price'] ?></td>
            <td><?= $value['is_active'] ?></td>
            <td><a href="index.php?route=book/edit&id=<?=$value['id']?>">Редагувати</a></td>
            <td><a href="index.php?route=book/delete&id=<?=$value['id']?>"">Видалити</a></td>
        </tr>
    <?php endforeach;?>
</table></table>
    <tr>
        <?php   $nbsp = '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp';
                if (!isset($_GET['page'])):
                    $page = 1;
                else:
                    $page = $_GET['page'];
                endif;
        ?>
        <td><?= $nbsp ?><a href="index.php?route=book/index&page=1"><b>
                    <?= $page == 1 ? '<b class="bold">1</b>' : 1 ?></b></a></td>
        <td><?= $nbsp ?><a href="index.php?route=book/index&page=2"><b>
                    <?= $page == 2 ? '<b class="bold">2</b>' : 2 ?></b></a></td>
        <td><?= $nbsp ?><a href="index.php?route=book/index&page=3"><b>
                    <?= $page == 3 ? '<b class="bold">3</b>' : 3 ?></b></a></td>
        <?php if ($page == 1 || $page == 2): ?>
            <td><?= $nbsp ?><b>...</b></td>
        <?php elseif ($page == 3): ?>
        <td><?= $nbsp ?><a href="index.php?route=book/index&page=4"><b>4</b></a></td>
                <td><?= $nbsp ?><b>...</b></td>
        <?php elseif ($page == 4): ?>
        <td><?= $nbsp ?><a href="index.php?route=book/index&page=4"><b>
                    <?= $page == 4 ? '<b class="bold">4</b>' : 4 ?></b></a></td>
        <td><?= $nbsp ?><a href="index.php?route=book/index&page=5"><b>5</b></a></td>
                <td><?= $nbsp ?><b>...</b></td>
        <?php elseif ($page == 5): ?>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=4"><b>4</b></a></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=5"><b>
                        <?= $page == 5 ? '<b class="bold">5</b>' : 5 ?></b></a></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=6"><b>6</b></a></td>
            <td><?= $nbsp ?><b>...</b></td>
        <?php elseif ($page > 5 && $page < ($count_pages - 4)): ?>
            <td><?= $nbsp ?><b>...</b></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= $page - 1 ?> "><b><?= $page - 1 ?></b></a></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= $page ?>"><b class="bold">
                        <?= $page ?></b></a></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= $page + 1 ?>"><b><?= $page + 1 ?></b></a></td>
            <td><?= $nbsp ?><b>...</b></td>
        <?php elseif ($page == ($count_pages - 4)): ?>
            <td><?= $nbsp ?><b>...</b></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= $page - 1 ?> "><b><?= $page - 1 ?></b></a></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= $page ?>"><b class="bold"><?= $page ?></b></a></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= $page + 1 ?>"><b><?= $page + 1 ?></b></a></td>
        <?php elseif ($page == ($count_pages - 3)): ?>
            <td><?= $nbsp ?><b>...</b></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= $page - 1 ?> "><b><?= $page - 1 ?></b></a></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= $page ?>"><b class="bold"><?= $page ?></b></a></td>
        <?php elseif ($page == ($count_pages - 2)): ?>
            <td><?= $nbsp ?><b>...</b></td>
            <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= $page - 1 ?> "><b><?= $page - 1 ?></b></a></td>
        <?php else: ?>
            <td><?= $nbsp ?><b>...</b></td>
        <?php endif; ?>
        <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= ($count_pages - 2) ?>">
                <b><?= $page == ($count_pages - 2) ? "<b class=\"bold\">{$page}</b>" : ($count_pages - 2) ?>
                </b></a></td>
        <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= ($count_pages - 1) ?>">
                <b><?= $page == ($count_pages - 1) ? "<b class=\"bold\">{$page}</b>" : ($count_pages - 1) ?>
                </b></a></td>
        <td><?= $nbsp ?><a href="index.php?route=book/index&page=<?= ($count_pages) ?>">
                <b><?= $page == $count_pages ? "<b class=\"bold\">{$page}</b>" : $count_pages ?>
                </b></a></td>

    </tr>

</body>
</html>