<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post">
    <button  formmethod="get" name="route" value="book/add"><b>Додати нову книгу до каталогу.</b></button>
</form>
<table border="3" width="100%">
    <tr>
        <th bgcolor="#87cefa" >Номер книги</th>
        <th bgcolor="#87cefa">Назва книги</th>
        <th bgcolor="#87cefa">Ціна</th>
        <th bgcolor="#87cefa">Наявність</th>
        <th bgcolor="#87cefa" align="сenter" colspan="2">Дії</th>

    </tr>

    <?php
    foreach ($array_book as $key => $value):
        ?>
        <tr>
            <td><?= $value['id'] ?></td>
            <td><a href="#" title="<?= $value['description'] ?>"><?= $value['title'] ?></a></td>
            <td><?= $value['price'] ?></td>
            <td><?= $value['is_active'] ?></td>
            <td><a href="index.php?route=book/edit&id=<?=$value['id']?>">Редагувати</a></td>
            <td><a href="index.php?route=book/delete&id=<?=$value['id']?>"">Видалити</a></td>
        </tr>
    <?php endforeach;?>
</table></table>
    <tr>
        <?php for ($i = 1; $i<=$count_pages; $i++): ?>
        <td>&nbsp&nbsp<a href="index.php?route=book/index&page=<?=$i ?>"><b><?=$i ?></b></a></td>
        <?php endfor; ?>
    </tr>

</body>
</html>