<!DOCTYPE html>
<html lang="en">
<head>
    <meta  http-equiv=content-type content="text/html; charset=UTF-8">
    <title>Title</title>
    <style>
        .input {
            width: 180px;
            height: 25px;
            text-decoration: none;
            font-size: large;
            color: blue;
            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: lightcyan;

        }
        input:focus {
            border: 2px solid;
            color: red;
            border-radius: 6px;
            outline: none;
        }

        .button {
        display: inline-block;
        color: black;
        font-size: medium ;
        font-family: Arial, Verdana;
        font-weight: 500 ;
        text-decoration: none;
        padding: 7px 25px;
        outline: none;

        border-width: 2px;
        border-style: solid;
        border-color: blue;
        border-radius: 6px;
        background: lightblue;
        transition: 0.2s;
        }
        button:hover { background: deepskyblue; }
        button:active { background: lightgoldenrodyellow; }

        .style-small {
            font-family: "Arial Black";
            color: darkcyan;
            font-size: small;
            font-weight: bold;
        }

        .style-middle {
            font-family: "Arial Black";
            color: darkcyan;
            font-size: larger;
            font-weight: bold;
        }
        .message {
            background: #f2dede;
            font-family: "Arial Black";
            color: indianred ;
            font-size: larger;
            font-weight: bold;
            padding: 5px;
            width: 30%;
            border-style: solid;
            border-color: crimson ;
            border-width: 1px;
            border-radius: 5px;
        }

    </style>

</head>
<body>

<?php

    require 'captcha.php';

    \Library\Session::setContent('REQUEST_URI', $_SERVER['REQUEST_URI']);


    if (isset($_SESSION['first'])):
        $increase = \Library\Session::getContent('first');
        $increase = ++$increase;
        \Library\Session::setContent('first', $increase);
    else:
        \Library\Session::setContent('first', 1);
    endif;
    if (\Library\Session::getContent('first') > 1):
        $msg_err = \Library\Session::getMessage();
        if ($msg_err !== null):
            echo '<div class="message">', $msg_err, '</div>';
        endif;
        \Library\Session::setMessage(null);
    elseif (isset($_SESSION['registered']) && \Library\Session::getContent('first') == 1):
        $msg_err = \Library\Session::getContent('registered');
        echo '<div class="message">', $msg_err, '</div>';
        \Library\Session::remove('registered');
?>
        <script>
                sessionStorage.setItem('login_stor', '');
                sessionStorage.setItem('email_stor', '');
                sessionStorage.setItem('pass_stor', '');
                sessionStorage.setItem('pass_re_stor', '');
        </script>

<?php
    endif;
?>

<h2 class="style-middle"><i>Реєстрація нового користувача</i></h2>
<form method="post">
    <br>
    <label class="style-small">Введіть своє майбутнє ім'я (логін):</label><br>
    <input class="input" id="login_id" type="text" onchange="change_login()" autofocus name="login"><br><br>

    <script>
        function change_login()
        {
            var login_stor = document.getElementsByTagName('input')[1].value;
//            alert(document.getElementsByTagName('input')[1].value);
            sessionStorage.setItem('login_stor', login_stor);
        }
        document.getElementsByTagName('input')[1].value = sessionStorage.getItem('login_stor');
    </script>
    <label class="style-small">Введіть свою електронну пошту: </label><br>
    <input class="input" id="email_id" type="email" onchange="change_email()" name="email">
    <br><br>
    <script>
        function change_email()
        {
            var email_stor = document.getElementsByTagName('input')[2].value;
            sessionStorage.setItem('email_stor', email_stor);
        }
        document.getElementsByTagName('input')[2].value = sessionStorage.getItem('email_stor');
    </script>
    <label class="style-small">Введіть пароль:</label><br>
    <input class="input" id="pass_text_id" type="password" onchange="change_pass()" name="password"><br><br>
    <script>
        function change_pass()
        {
            var pass_stor = document.getElementsByTagName('input')[3].value;
            sessionStorage.setItem('pass_stor', pass_stor);
        }
        document.getElementsByTagName('input')[3].value = sessionStorage.getItem('pass_stor');
    </script>
    <label class="style-small">Повторіть пароль:</label><br>
    <input class="input" id="pass_text_re_id" type="password" onchange="change_pass_re()" name="password_repeat"><br><br>
    <script>
        function change_pass_re()
        {
            var pass_re_stor = document.getElementsByTagName('input')[4].value;
            sessionStorage.setItem('pass_re_stor', pass_re_stor);
        }
        document.getElementsByTagName('input')[4].value = sessionStorage.getItem('pass_re_stor');
        sessionStorage.setItem('passview', 0);
    </script>
    <input type="checkbox" name="passview" onclick="passview_()">&nbsp
        Показати пароль<br>
    <img style="width: 10%; padding: 7px 0 0 0;" id="captcha" src='captcha.png'>
    <label for="recap" >
    <a  href="/index.php?route=site/register" id="recap"><img style=" width: 4.7%" src="\recaptcha.png" alt=""></a><br><br>
    </label>

    <script>
        function passview_()
        {
            if (!sessionStorage.getItem('passview') || sessionStorage.getItem('passview') == 0){
                document.getElementById('pass_text_id').outerHTML =
                    "<input class='input' id='pass_text_id' type='text' onchange='change_pass()' name='password'>";
                document.getElementById('pass_text_re_id').outerHTML =
                    "<input class='input' id='pass_text_re_id' type='text' onchange='change_pass_re()' name='password_repeat' >";

                sessionStorage.setItem('passview', 1);
            }
            else {
                document.getElementById('pass_text_id').outerHTML =
                    "<input class='input' id='pass_text_id' type='password' onchange='change_pass()' name='password' >";
                document.getElementById('pass_text_re_id').outerHTML =
                    "<input class='input' id='pass_text_re_id' type='password' onchange='change_pass_re()' name='password_repeat' >";

                sessionStorage.setItem('passview', 0);

            }
            document.getElementsByTagName('input')[3].value = sessionStorage.getItem('pass_stor');
            document.getElementsByTagName('input')[4].value = sessionStorage.getItem('pass_re_stor');
        }
    </script>

    <label class="style-small">Введіть код із зображення</label><br>
    <input class="input" type="text" name="code" ><br><br>

    <button class="button" >Зареєструватись</button>

</form>


</body>
</html>