<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .meesage {
            width: 100%;
            height: 50px;
            background-color: #e7c3c3;
            padding: 10px;
            margin-top: 1%;
        }

    </style>
</head>
<body>

<form method="post">
    <?php if (isset($_COOKIE['username_in'])): ?>
        <h2>Ви авторизовані як <?=$_COOKIE['username_in']?></h2>
        <br>
    <?php else:
        if ($logerr !== null):
            echo '<div class="meesage"><b>', $logerr, '</b></div>' ;
        endif;
        ?>
        <h2>Авторизація</h2>
        <label for="login">Логін</label><br>
        <input type="text" name="login" id="login"><br><br>
        <label for="email">E_mail</label><br>
        <input type="email" name="email" id="login"><br><br>
        <label for="password">Пароль</label><br>
        <input type="password" name="password" id="password"><br><br>

        <button>Авторизуватись</button>
    <?php endif;?>
</form>


</body>
</html>