<!DOCTYPE html>
<html lang="en">
<head>
    <meta  http-equiv=content-type content="text/html; charset=UTF-8">
    <title>Title</title>
    <style>
        .input {
            width: 180px;
            height: 25px;
            text-decoration: none;
            font-size: large;
            color: blue;
            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: lightcyan;

        }
        input:focus {
            border: 2px solid;
            color: red;
            border-radius: 6px;
            outline: none;
        }

        .button {
        display: inline-block;
        color: black;
        font-size: medium ;
        font-family: Arial, Verdana;
        font-weight: 500 ;
        text-decoration: none;
        padding: 7px 25px;
        outline: none;

        border-width: 2px;
        border-style: solid;
        border-color: blue;
        border-radius: 6px;
        background: lightblue;
        transition: 0.2s;
        }
        button:hover { background: deepskyblue; }
        button:active { background: lightgoldenrodyellow; }

        .style-small {
            font-family: "Arial Black";
            color: darkcyan;
            font-size: small;
            font-weight: bold;
        }

        .style-middle {
            font-family: "Arial Black";
            color: darkcyan;
            font-size: larger;
            font-weight: bold;
        }
        .message {
            background: #f2dede;
            font-family: "Arial Black";
            color: indianred ;
            font-size: larger;
            font-weight: bold;
            padding: 5px;
            width: 30%;
            border-style: solid;
            border-color: crimson ;
            border-width: 1px;
            border-radius: 5px;
        }
    </style>

</head>
<body>

    <?php

    require 'captcha.php';

    \Library\Session::setContent('REQUEST_URI', $_SERVER['REQUEST_URI']);

    if (isset($_SESSION['first'])):
        $increase = \Library\Session::getContent('first');
        $increase = ++$increase;
        \Library\Session::setContent('first', $increase);
    else:
        \Library\Session::setContent('first', 1);
    endif;

    if (\Library\Session::getContent('first') > 1):
        $msg_err = \Library\Session::getMessage();
        if ($msg_err !== null):
            echo '<div class="message">', $msg_err, '</div>';
        endif;
    elseif (isset($_SESSION['registered']) && \Library\Session::getContent('first') == 1):
        $msg_err = \Library\Session::getContent('registered');
//        \Library\Session::remove('registered');
        if ($msg_err !== null):
            echo '<div class="message">', $msg_err, '</div>';
        endif;
    endif;

    ?>

<h2 class="style-middle"><i>Реєстрація нового користувача</i></h2>
<form method="post">
    <br>
    <label class="style-small">Введіть своє майбутнє ім'я (логін):</label><br>
    <input class="input" id="login_id" type="text" autofocus name="login" value="<?= $login_for_form ?>"><br><br>
    <label class="style-small">Введіть свою електронну пошту: </label><br>
    <input class="input" id="email_id" type="email" name="email" value="<?= $email_for_form ?>"><br><br>
        <label class="style-small">Введіть пароль:</label><br>
        <input class="input" id="pass_text_id" type="password" name="password" value="<?= $pass_for_form ?>"><br><br>
        <label class="style-small">Повторіть пароль:</label><br>
        <input class="input" id="pass_text_r_id" type="text" name="password_repeat" value="<?= $pass_r_for_form ?>"><br><br>
        <input type="checkbox" name="passview" onclick="passview_()">&nbsp
        Показати пароль<br><br>
    <img id="captcha" src='captcha.png'>
    <a href="/index.php?route=site/register">
            Оновити зображення</a><br><br>
    <script>
        function passview_()
        {
            var pass_stor = document.getElementsByTagName('input')[2].value;
            sessionStorage.setItem('pass_stor', pass_stor);
            if (!sessionStorage.getItem('passview') || sessionStorage.getItem('passview') == 0){
                document.getElementById('pass_text_id').outerHTML =
                    "<input class='input' id='pass_text_id' type='text' name='password' value=''>";
            document.getElementsByTagName('input')[2].value = sessionStorage.getItem('pass_stor');

                sessionStorage.setItem('passview', 1);
            }
            else {
                document.getElementById('pass_text_id').outerHTML =
                    "<input class='input' id='pass_text_id' type='password' name='password' value=''>";
                document.getElementsByTagName('input')[2].value = sessionStorage.getItem('pass_stor');

                sessionStorage.setItem('passview', 0);

            }
//            alert(document.getElementById('pass_text_id').outerHTML);
//            document.getElementById('pass_text_id').outerHTML =
//                "<input class='input' id='pass_text_id' type='password' name='password' value=''>";
//            alert(document.getElementById('pass_text_id').outerHTML);
//            alert(document.getElementsByTagName('input')[0].type('text'));
//            var log_stor = document.getElementsByTagName('input')[0].;
//            if (!sessionStorage.getItem('login_storage')){
//                sessionStorage.setItem('login_storage', log_stor);
//            }
//
//            alert(log_stor);
//            var a = sessionStorage.getItem('login_storage');
//
//            alert (a);
////            $.get('index.php?route=site/register', {message:a}, function(data) {
////                alert('Сервер ответил: ' + data);
////            });
//
////            document.getElementsByTagName('input')[0].value = a;
//            //            document.getElementById('captcha').outerHTML = "<img id='captcha' src='cap.png'>";
//            $('login_id').val(a);
//            location.href='index.php?route=site/register&passview=1';
        }
    </script>

    <label class="style-small">Введіть код із зображення</label><br>
    <input class="input" type="text" name="code" ><br><br>

    <button class="button">Зареєструватись</button>

</form>


</body>
</html>