<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .meesage-err {
            width: 97%;
            height: 50px;
            background-color: #e7c3c3;
            padding: 10px;
            margin-top: 1%;
        }
        .meesage {
            width: 97%;
            height: 50px;
            background-color: lightgreen;
            padding: 10px;
            margin-top: 1%;
        }
        .layer {
            width: 97%;
            height: 300px;
            background-color: #c1e2b3;
            padding: 10px;
            overflow-y: scroll;
            margin-top: 1%;
        }
        label {
            /*width: 5px;*/
            /*height: 20px;*/
            position: relative;
        }
        input[type="checkbox"] + span {
            position: absolute;
            left: 0; top: 0;
            width: 80%;
            height: 100%;
            background: url(/switch_off.png);
            cursor: pointer;
        }
        input[type="checkbox"]:checked + span {
            background: url(/switch_on.png);
        }
        .button-add {
            display: inline-block;
            color: black;
            font-size: large;
            text-decoration: none;
            padding: 5px 20px;
            outline: none;
            cursor: pointer;
            border-width: 2px;
            border-style: solid;
            border-color: black;
            border-radius: 6px;
            background: aquamarine;
            transition: 0.3s;
        }
        .button-add:hover { background: lightgreen; }
        .button-add:active { background: white; }

        .button-page-plus {
            display: inline-block;
            color: black;
            font-size: large;
            font-family: Arial, Verdana;
            font-weight: 500 ;
            text-decoration: none;
            padding: 0.03% 0.53%;
            outline: none;

            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: aqua;
            transition: 0.2s;
        }
        .button-page-plus:hover { background: cornflowerblue; color: limegreen}
        .button-page-plus:active { background: snow; }

        .button-page-minus {
            display: inline-block;
            color: black;
            font-size: large;
            font-family: Arial, Verdana;
            font-weight: 500 ;
            text-decoration: none;
            padding: 0.05% 0.7%;
            outline: none;

            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: aqua;
            transition: 0.2s;
        }
        .button-page-minus:hover { background: cornflowerblue; color: limegreen}
        .button-page-minus:active { background: snow; }

        .button-edit {
            display: inline-block;
            color: black;
            font-size: small ;
            font-family: Arial, Verdana;
            font-weight: 300 ;
            text-decoration: none;
            padding: 2px 15px;
            outline: none;

            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: paleturquoise ;
            transition: 0.2s;
        }
        .button-edit:hover { background: cornflowerblue; color: limegreen}
        .button-edit:active { background: snow; }
        .button-delete {
            display: inline-block;
            color: black;
            font-size: small ;
            font-family: Arial, Verdana;
            font-weight: 300 ;
            text-decoration: none;
            padding: 2px 15px;
            outline: none;

            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: darksalmon ;
            transition: 0.2s;
        }
        .button-delete:hover { background: red; }
        .button-delete:active { background: snow; }



    </style>
</head>

<body>
<?php
\Library\Session::setContent('REQUEST_URI', $_SERVER['REQUEST_URI']);
?>

    <?php
    $message = \Library\Session::getMessage();
    if ($message !== null):
        if ($message == 'delete'):
            $user_delete = \Library\Session::getContent('user_delete');
            echo '<div class="meesage">';
            echo "<b>Коментар від \"<i>{$user_delete}</i>\" видалено</b>";
            echo '</div>';
        elseif($message == 'add'):
            $user_add_comment = \Library\Session::getContent('user');
            echo '<div class="meesage">';
            echo "<b>Коментар від \" <i>{$user_add_comment}</i>\" додано</b>";
            echo '</div>';
        else:
            echo '<div class="meesage-err">';
            echo "<b>{$message}</b>";
            echo '</div>';
        endif;
    endif;

    ?>


<form method="post">
    <div class="layer">
        <?php
        $i = 0;
        \Library\Session::setContent('desc', 'comments');
        foreach ($find_comments as $arr):
            echo 'Дописувач:&nbsp', '<b>', $arr["username"], '</b>';
            if ($arr['checkbox_state'] == 'on'):
                echo "&nbsp&nbsp E-mail:", "<b>{$arr['email']}</b>", '&nbsp';
            endif;
            echo '&nbsp&nbspКоментар додано:&nbsp', $arr["time_stamp"];
            $i = $arr["id"];
            $u = $arr["username"];
            echo '<br>';
            echo 'Додає коментар:', '<br><br>';
            echo '<b><i>', $arr["comment_text"], '</i></b>', '<br><br>';
            if (isset($_COOKIE['username_in'])):
                echo "<a class='button-delete' href=\"index.php?route=comment/index&delete=$i&user_delete=$u \">
                <b>Видалити&nbsp&nbsp&nbsp</b></a>";
            endif;
            echo '&nbsp&nbsp Рейтинг комантаря: &nbsp';
            echo '<b>', $arr["rating"], '</b>';
            echo ' &nbsp&nbsp Зміна рейтингу: &nbsp&nbsp&nbsp';
            echo "<a class='button-page-plus' href=\"index.php?route=comment/index&r_plus=$i \">
            <b>+</a>";
            echo '&nbsp&nbsp&nbsp';
            echo "<a class='button-page-minus' href=\"index.php?route=comment/index&r_minus=$i \">
            <b>-</b></a>";
            echo '<br>', '<div style="width: 100%; height: 2px; background: darkgreen;">&nbsp</div>', '<br>';
        endforeach;
        ?>
    </div>

    &nbsp&nbsp<font size="5">Залиште коментар на сторінці:</font>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

    <br>
    &nbsp&nbsp<b>Логін</b><br>
    &nbsp&nbsp<input type="text" name="username"><br><br>
    &nbsp&nbsp<b>E-mail</b><br>
    &nbsp&nbsp<input type="email" name="email"> &nbsp&nbsp&nbsp
    <label><input type="checkbox" name="email_on" >
        <span></span></label>&nbspПоказувати E-mail в коментарях
    <br><br>
    &nbsp&nbsp<textarea name="comment_text"  cols="130" rows="7" placeholder="Текст коментаря" autofocus></textarea>
    <br><br>
    &nbsp&nbsp<input class="button-add" type="submit" value="Додати коментар">
    <br><br>
</form>

</body>
</html>