<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MVC - Victor</title>
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/starter-template.css" rel="stylesheet">

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" ><?=isset($_COOKIE['username_in']) ? "Вітаємо, ". $_COOKIE['username_in'] : '!' ?></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="index.php">Головна</a></li>
                <li><a href="/index.php?route=book/index">Книги</a></li>
                <li><a href="/index.php?route=comment/index">Коментарі</a></li>
                <li><a href="/index.php?route=gallery/index">Галерея</a></li>
                <?php if (!isset($_COOKIE['username_in'])): ?>
                <li><a href="/index.php?route=site/login">Авторизація</a></li>
                <li><a href="/index.php?route=site/register">Реєстрація</a></li>
                <?php else: ?>
                <li><a href="/index.php?route=site/login&logmsg=out">Вихід</a></li>
                <?php endif; ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<br>
<hr class="hr">

<?= $content ?>

<hr class="hr">

<!-- JavaScript-ядро Bootstrap
================================================== -->
<!-- Розміщуйте підключення JavaScript в кінці документа щоб сторінки завантажувались швидше -->
<script src="/js/jquery-3.1.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>

</body>
</html>