<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>MVC - Victor</title>
    <style>
         body{
            margin: 0;
        }
        .menu{
            background: black;
            width: 100%;
            float: left;
            position: fixed;
            padding: 1%;
            /*border-radius: 5px;*/
        }
        .content{
            background: lightyellow;
            border-radius: 5px;
            width: 99%;
            height: 50%;
            padding: 0 0 1% 1%;
            margin: 3% 0 0 0;
            float: left;
        }
        .a-menu {
            text-decoration: none;
            color: darkgray;
            font-family: Arial, Verdana ;
            font-size: larger ;
        }
        a.a-menu:hover{color: white;}
        a.a-menu:active {background: lightskyblue;}

    </style>
</head>
<body>
<!--<header class="box">-->
        <div class="menu">
            <?php if (isset($_COOKIE['username_in'])): ?>
            <label class="a-menu">Вітаємо <?= $_COOKIE['username_in'] ?></label>$nbsp$nbsp
            <?php else: ?>
            <label class="a-menu"> ! </label>$nbsp$nbsp
            <?php endif; ?>


                <a class="a-menu" href="index.php">Головна</a>$nbsp$nbsp
                <a class="a-menu" href="/index.php?route=book/index">Книги</a>$nbsp$nbsp
                <a class="a-menu" href="/index.php?route=comment/index">Коментарі</a>$nbsp$nbsp
                <a class="a-menu" href="/index.php?route=gallery/index">Галерея</a>$nbsp$nbsp
                <?php if (!isset($_COOKIE['username_in'])): ?>
                <a class="a-menu" href="/index.php?route=site/login">Авторизація</a>$nbsp$nbsp
<!--                <a class="a" href="/index.php?route=site/register">Реєстрація</a>$nbsp$nbsp-->
                <?php else:
                \Library\Session::setContent('logmsg', 'out');
                ?>
                <a class="a-menu" href="/index.php?route=site/login">Вихід</a>$nbsp$nbsp
                <?php endif; ?>

        </div>
<!--</header>-->
<br>
<div class="content">
<?= $content ?>
</div>

<!-- JavaScript-ядро Bootstrap
================================================== -->
<!-- Розміщуйте підключення JavaScript в кінці документа щоб сторінки завантажувались швидше -->
<!--<script src="/js/jquery-3.1.1.min.js"></script>-->
<!--<script src="/js/bootstrap.min.js"></script>-->

</body>
</html>