<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MVC - Victor</title>
    <style>
        .box {
            width: auto;

        }
        .menu{
            background: black;
            width: 98%;
            float: left;
            padding: 1%;
            border-radius: 5px;
        }
        .content{
            background: #f7ecb5;
            border-radius: 5px;
            width: 99%;
            height: 50%;
            padding: 0 0 1% 1%;
            margin: 1% 0 0 0;
            float: left;
        }
        .a {
            text-decoration: none;
            color: darkgray;
            font-family: Arial, Verdana ;
            font-size: larger ;
        }
        a:hover{
            color: white;
        }
        a:active {
            background: lightskyblue;
        }

    </style>
</head>
<body>
<div class="box">
        <div class="menu">

                <a class="a" href="index.php">Головна</a>$nbsp$nbsp
                <a class="a" href="/index.php?route=book/index">Книги</a>$nbsp$nbsp
                <a class="a" href="/index.php?route=comment/index">Коментарі</a>$nbsp$nbsp
                <a class="a" href="/index.php?route=gallery/index">Галерея</a>$nbsp$nbsp
                <?php if (!isset($_COOKIE['username_in'])): ?>
                <a class="a" href="/index.php?route=site/login">Авторизація</a>$nbsp$nbsp
                <a class="a" href="/index.php?route=site/register">Реєстрація</a>$nbsp$nbsp
                <?php else: ?>
                <a class="a" href="/index.php?route=site/login&logmsg=out">Вихід</a>$nbsp$nbsp
                <?php endif; ?>

        </div>
<br>
<div class="content">
<?= $content ?>
</div>
</div>
<!-- JavaScript-ядро Bootstrap
================================================== -->
<!-- Розміщуйте підключення JavaScript в кінці документа щоб сторінки завантажувались швидше -->
<script src="/js/jquery-3.1.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>

</body>
</html>