<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .meesage {
            width: 97%;
            height: 50px;
            background-color: #e7c3c3;
            padding: 10px;
            margin-top: 1%;
        }
        .layer {
            width: 97%;
            height: 300px;
            background-color: #c1e2b3;
            padding: 10px;
            overflow-y: scroll;
            margin-top: 1%;
        }
        label {
            width: 20px;
            height: 20px;
            position: relative;
        }
        input[type="checkbox"] + span {
            position: absolute;
            left: 0; top: 0;
            width: 100%;
            height: 100%;
            background: url(/switch_off.png);
            cursor: pointer;
        }
        input[type="checkbox"]:checked + span {
            background: url(/switch_on.png);
        }

    </style>
</head>

<body>
<div class="meesage">
    <?php
    if (isset($_GET['msg'])):
        if ($_GET['msg'] == 'delete'):
            echo '<b>Коментар видалено</b>';
        elseif($_GET['msg'] == 'add'):
            echo "<b>Коментар від \" <i>{$_GET['user']}</i>\" додано</b>";
        else:
            echo $_GET['msg'];
        endif;
    endif;

    ?>
</div>


<form method="post">
    <div class="layer">
        <?php
        $i = 0;
        foreach ($find_comments as $arr):
            echo 'Дописувач:&nbsp', '<b>', $arr["username"], '</b>';
            if ($arr['checkbox_state'] == 'on'):
                echo "&nbsp&nbsp E-mail:", "<b>{$arr['email']}</b>", '&nbsp';
            endif;
            echo '&nbsp&nbspКоментар додано:&nbsp', $arr["time_stamp"];
            $i = $arr["id"];
            echo '<br>';
            echo 'Додає коментар:', '<br><br>';
            echo '<b><i>', $arr["comment_text"], '</i></b>', '<br><br>';
            echo "<a href=\"index.php?route=comment/index&delete=$i \">
            <b>Видалити&nbsp&nbsp&nbsp</b></a>";
            echo '&nbsp&nbsp Рейтинг комантаря: &nbsp';
            echo '<b>', $arr["rating"], '</b>';
            echo ' &nbsp&nbsp Зміна рейтингу: &nbsp&nbsp&nbsp';
            echo "<a href=\"index.php?route=comment/index&r_plus=$i \">
            <b><big><big>+</big></big></b></a>";
            echo '&nbsp&nbsp&nbsp';
            echo "<a href=\"index.php?route=comment/index&r_minus=$i \">
            <b><big><big>-</big></big></b></a>";
            echo '<br>', '<div style="width: 100%; height: 2px; background: darkgreen;">&nbsp</div>', '<br>';
        endforeach;
        ?>
    </div>

    &nbsp&nbsp<font size="5">Залиште коментар на сторінці:</font>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

    <br>
    &nbsp&nbsp<b>Логін</b><br>
    &nbsp&nbsp<input type="text" name="username"><br><br>
    &nbsp&nbsp<b>E-mail</b><br>
    &nbsp&nbsp<input type="email" name="email"> &nbsp&nbsp&nbsp
    <label><input type="checkbox" name="email_on" >
        <span></span></label>&nbspПоказувати E-mail в коментарях
    <br><br>
    &nbsp&nbsp<textarea name="comment_text"  cols="130" rows="7" placeholder="Текст коментаря" autofocus></textarea>
    <br><br>
    &nbsp&nbsp<input type="submit" value="Додати коментар">
    <br><br>
</form>

</body>
</html>