<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .layer {
            width: 97%;
            height: 250px;
            background-color: #c1e2b3;
            /*padding: 5px;*/
            overflow-y: scroll;
            margin-top: 1%;
        }
        .button {
            display: inline-block;
            color: black;
            font-size: small ;
            font-family: Arial, Verdana;
            font-weight: 300 ;
            text-decoration: none;
            padding: 3px 15px;
            outline: none;

            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: lightblue;
            transition: 0.2s;
        }
        .button:hover { background: deepskyblue; }
        .button:active { background: lightgoldenrodyellow; }


    </style>
</head>
<body>
<br>
<br>
<br>
<b>Спортивні новини:</b> "<?= $array_s['title']?>"
<br>
<br>
<div style="width: 100%; height:auto">
    <div style="width: 100%; height: 200px; ">
        <img src="<?= $array_s['pics'] ?>" align="left" alt="NO FILE">
        <?php
        $id_user = 0;
        $name_cook_user = 0;
        echo $array_s['content'];
        if (isset($_COOKIE['username_in'])):
            $d_coockie = explode('-', $_COOKIE['username_in']);
            $id_user = $d_coockie['1'];
            $name_cook_user = $d_coockie['0'];
        endif;
        ?>

    </div>
    <b>Коментарі - <?= isset($count_comment['count'])? $count_comment['count'] : 0  ?>
    <div class="layer">
        <?php
        //        echo $name_cook_user;
        //
        //        var_dump($_POST);
        $desc = $_GET['description'];
        $page = $_GET['page'];
        $i = 0;
        $n = 1;
        $i_for_script_modify = -1;
        $count_user_feed = '';
        //        var_dump($array_feed);
        if ($array_feed !== null):
            foreach ($array_feed as $arr):
                ++$i_for_script_modify;
                echo 'Дописувач:&nbsp', '<b>', $arr["name_user"], '</b>';
                echo '&nbsp&nbspКоментар додано:&nbsp', $arr["time_stamp"];
                $i = $arr["id_user"];
                $u = $arr["name_user"]; ?><br>
                Додає коментар:<br><br>
                <textarea disabled name="feed" cols="100" rows="3"><?=$arr["user_comment"]?></textarea><br>
                <input type="hidden" name="user_modify_count" value="<?=$arr["name_user"]?>">
                <script>
                    function delete_fn()
                    {
                        confirm('Видалити коментар?');
                    }
                    function modify_fn(a)
                    {
//                        alert (a);
//                        alert ('Y');
//                        alert (sessionStorage.getItem(a));
                        document.getElementsByTagName('textarea')[a].outerHTML =
                            "<textarea name='feed' id='' cols='100' rows='3'>" + sessionStorage.getItem(a) + "</textarea><br>";
                        return;
                    }
                    var current_user = document.getElementsByName('user_modify_count')[<?= $i_for_script_modify ?>];
                    //                    alert('<?//= $name_cook_user ?>//');
                    //                    alert(current_user.value);
                    if ('<?= $name_cook_user ?>' == current_user.value) {
//                        alert ('Y');
                        document.getElementsByTagName('textarea')[<?=$i_for_script_modify?>].outerHTML =
                            "<form method='post'>"+
                            "<textarea disabled name='feed' id='' cols='100' rows='3'><?=$arr['user_comment']?></textarea><br>"+
                            "<button type='button' name= 'button' value = '<?=$i_for_script_modify?>'"+
                            "onclick = 'modify_fn(<?=$i_for_script_modify?>)' >Редагувати</button>"+
                            "<input type='hidden' name='id_news' value='<?= $array_s['id'] ?>'>"+
                            "<input type='hidden' name='category_news' value='sport'>"+
                            "<input type='hidden' name='id_user' value='<?= $id_user ?>'>"+
                            "<input type='hidden' name='update' value='update'>"+
                            "<input type='hidden' name='id' value='<?= $arr['id'] ?>'>"+
                            "<button type='submit'>Зберегти зміни</button>"+
                            "</form>"+
                            "<form method='post'>"+
                            "<input type='hidden' name='id' value='<?=$arr['id']?>'>"+
                            "<input type='hidden' name='delete' value='delete'>"+
                            "<button type='submit' onclick = 'delete_fn()'>Видалити</button>"+
                            "</form>";
                        sessionStorage.setItem('<?= $i_for_script_modify ?>', '<?= $arr['user_comment'] ?>' );
                    }
                </script>
                <?php
                echo '&nbsp&nbsp Рейтинг комантаря: &nbsp';
                echo '<b>', $arr["rating_user"], '</b>';
                echo ' &nbsp&nbsp Зміна рейтингу: &nbsp&nbsp&nbsp';
                echo '<br>', '<div style="width: 100%; height: 2px; background: darkgreen;">&nbsp</div>', '<br>';
            endforeach;
        endif;
        ?>
    </div>
    <?php
    \Library\Session::setContent('category', 'sport');
    \Library\Session::setContent('desc', $_GET['description']);
    \Library\Session::setContent('page', $_GET['page']);

    if (isset($_COOKIE['username_in'])):
    ?>
        <form method="post">
            <div style="padding: 1% 0 0 0">
                <b>Додати коментар</b>
                <textarea name="feed" id="feed" cols="115" rows="7"></textarea><br><br>
                <input type="hidden" name="id_news" value="<?= $array_s['id'] ?>">
                <input type="hidden" name="category_news" value="sport">
                <input type="hidden" name="id_user" value="<?= $id_user ?>">
            </div>
            <button class="button" type="submit">Відправити</button>
            <a class="button" href="/index.php?route=sport/index&page=<?=$_GET['page'] ?>">Повернутись до категорії</a>
        </form>
    <?php else: ?>
        <br><b>Для додавання коментарів, будь ласка, зареєструйтесь
            <a class="button" href="/index.php?route=site/register">зареєструйтесь</a>
            або
            <a class="button"
               href="/index.php?route=site/login&cat=sport&desc=<?= $_GET['description'] ?>&pg=<?= $_GET['page'] ?>">
                авторизуйтесь</a>.</b> <br><br>
        <a class="button" href="/index.php?route=sport/index&page=<?=$_GET['page'] ?>">Повернутись до категорії</a>
    <?php endif; ?>
</div>
<br>
<br>
<?php
if ($_SERVER['REQUEST_METHOD'] == 'POST'):
    $desc = $_GET['description'];
    $page = $_GET['page'];
    header("location: index.php?route=sport/read&description=$desc&page=$page");
    die;
endif;
?>
</body>
</html>