<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .bold {
            color: crimson;
            font-size: medium ;
        }

        .button-page {
            display: inline-block;
            color: black;
            font-size: small ;
            font-family: Arial, Verdana;
            font-weight: 300 ;
            text-decoration: none;
            padding: 7px 15px;
            outline: none;

            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: palegreen;
            transition: 0.2s;
        }
        a.button-page:hover { background: cornflowerblue; color: limegreen}
        a.button-page:active { background: snow; }

    </style>
</head>
<body>
<?php
\Library\Session::setContent('REQUEST_URI', $_SERVER['REQUEST_URI']);
if (!isset($_GET['page'])):
    $_GET['page'] = 1;
    $page = 1;
else:
    $page = $_GET['page'];
endif;

    $nbsp = '&nbsp&nbsp';?>

<div style="margin: 1% 0 2% 0"><b>Новини бізнесу</b></div>

<?php
foreach ($business as $value):
?>
    <a href="index.php?route=business/read&description=<?= $value['id'] ?>&page=<?= $page ?>"><?= $value['title'] ?><br><br></a>
<?php
endforeach;
?>
<tr>

    <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=1"><b>
    <?= $page == 1 ? '<b class="bold">1</b>' : 1 ?></b></a></td>
    <?php if ($count_pages > 1 && $page == 1): ?>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page + 1 ?>"><b><?= $page + 1 ?>
                </b></a></td>
        <td><?= $nbsp ?><b class="bold2">&nbsp.&nbsp.&nbsp.&nbsp</b></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= ($count_pages) ?>">
                <b><?= $page == $count_pages ? "<b class=\"bold\">{$page}</b>" : $count_pages ?></b></a></td>
    <?php elseif ($count_pages > 1 && $page == 2): ?>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page ?>"><b class="bold"><?= $page ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page + 1 ?>"><b><?= $page + 1 ?>
                </b></a></td>
        <td><?= $nbsp ?><b class="bold2">&nbsp.&nbsp.&nbsp.&nbsp</b></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= ($count_pages) ?>">
                <b><?= $page == $count_pages ? "<b class=\"bold\">{$page}</b>" : $count_pages ?></b></a></td>
    <?php elseif ($count_pages > 1 && $page == 3 && $page < $count_pages): ?>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page-1 ?>"><b><?= $page-1 ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page ?>"><b class="bold"><?= $page ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page + 1 ?>"><b><?= $page + 1 ?>
                </b></a></td>
        <td><?= $nbsp ?><b class="bold2">&nbsp.&nbsp.&nbsp.&nbsp</b></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= ($count_pages) ?>">
                <b><?= $page == $count_pages ? "<b class=\"bold\">{$page}</b>" : $count_pages ?></b></a></td>
    <?php elseif ($count_pages > 1  && $page < $count_pages - 2): ?>
        <td><?= $nbsp ?><b class="bold2">&nbsp.&nbsp.&nbsp.&nbsp</b></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page-1 ?>"><b><?= $page-1 ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page ?>"><b class="bold"><?= $page ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page + 1 ?>"><b><?= $page + 1 ?>
                </b></a></td>
        <td><?= $nbsp ?><b class="bold2">&nbsp.&nbsp.&nbsp.&nbsp</b></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= ($count_pages) ?>">
                <b><?= $page == $count_pages ? "<b class=\"bold\">{$page}</b>" : $count_pages ?></b></a></td>
    <?php elseif ($count_pages > 1  && $page == $count_pages - 2): ?>
        <td><?= $nbsp ?><b class="bold2">&nbsp.&nbsp.&nbsp.&nbsp</b></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page - 1 ?>"><b><?= $page - 1 ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page ?>"><b class="bold"><?= $page ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page + 1 ?>"><b><?= $page + 1 ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= ($count_pages) ?>">
                <b><?= $page == $count_pages ? "<b class=\"bold\">{$page}</b>" : $count_pages ?></b></a></td>
    <?php elseif ($count_pages > 1  && $page == $count_pages - 1): ?>
        <td><?= $nbsp ?><b class="bold2">&nbsp.&nbsp.&nbsp.&nbsp</b></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page - 1 ?>"><b><?= $page - 1 ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page ?>"><b class="bold"><?= $page ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= ($count_pages) ?>">
                <b><?= $page == $count_pages ? "<b class=\"bold\">{$page}</b>" : $count_pages ?></b></a></td>
    <?php else: ?>
        <td><?= $nbsp ?><b class="bold2">&nbsp.&nbsp.&nbsp.&nbsp</b></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= $page - 1 ?>"><b><?= $page - 1 ?>
                </b></a></td>
        <td><?= $nbsp ?><a class="button-page" href="index.php?route=business/index&page=<?= ($count_pages) ?>">
                <b><?= $page == $count_pages ? "<b class=\"bold\">{$page}</b>" : $count_pages ?></b></a></td>
  <?php endif; ?>
</tr>


</body>
</html>