<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .input {
            width: 180px;
            height: 25px;
            text-decoration: none;
            font-size: large;
            color: blue;
            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: lightcyan;
            z-index: -1;

        }
        input:focus {
            border: 2px solid;
            color: red;
            border-radius: 6px;
            outline: none;
        }

        .button {
            display: inline-block;
            color: black;
            font-size: medium ;
            font-family: Arial, Verdana;
            font-weight: 500 ;
            text-decoration: none;
            padding: 7px 25px;
            outline: none;

            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: lightblue;
            transition: 0.2s;
        }
        .button:hover { background: deepskyblue; }
        .button:active { background: lightgoldenrodyellow; }

        .buttonup {
        }
        .buttonUpLabel {
            width: 10.7%;
            height: 20px;
            overflow: inherit;
            display: inline-block;
            color: black;
            font-size: medium ;
            font-family: Arial, Verdana;
            font-weight: 500 ;
            text-decoration: none;
            padding: 7px 25px;
            /*outline: none;*/
            border-width: 2px;
            border-style: solid;
            border-color: blue;
            border-radius: 6px;
            background: #f2dede ;
            transition: 0.2s;
        }
        .buttonUpLabel:hover { background: lawngreen; }
        .buttonUpLabel:active { background: lightgoldenrodyellow; }
        .checkbox {
            width: 40px;
            height: 25px;
        }

        .style-small {
            font-family: "Arial Black";
            color: darkcyan;
            font-size: small;
            font-weight: bold;
        }

        .style-middle {
            font-family: "Arial Black";
            color: darkcyan;
            font-size: larger;
            font-weight: bold;
        }
        .message {
            background: #f2dede;
            font-family: "Arial Black";
            color: indianred ;
            font-size: larger;
            font-weight: bold;
            padding: 5px;
            width: 30%;
            border-style: solid;
            border-color: crimson ;
            border-width: 1px;
            border-radius: 5px;
        }
   </style>

</head>
<body>
<?php
\Library\Session::setContent('REQUEST_URI', $_SERVER['REQUEST_URI']);
?>


<div style="margin-top: 10px">
    <h2 class="style-middle">Галерея</h2>
    <p class="style-small">
        !Увага! Файли розміром більше 2 Мб та файли відмінні від зображень завантажені не будуть.
    </p>
    <?php
        if ($over !== '' && $over !== null):
            echo "<div class=\"message\"> $over </div>";
        endif;
    ?>

</div>

<form enctype="multipart/form-data" method="post" id = "gallery">
    <br>
    <label for="up" class="buttonUpLabel">Вибрати файли
    <input name="file[]" type="file"  multiple style="opacity: 0; z-index: -1" id="up">
    </label>
    <br>
    <button class="button">Додати до галереї </button>
    <hr>

    <?php

    $current_dir = getcwd();
    chdir($current_dir . '\\gallery');
    $current_dir = getcwd();
    $open_dir = opendir($current_dir);
    $count = 1;
    while (($item_dir = readdir($open_dir)) !== false):
        if (is_file($item_dir) == 1):
            $checkbox = $count;
            $current_file = "\\gallery\\{$item_dir}";
            ?>

            <a href= "<?= $current_file; ?>" target='_blank'><img src = '<?= $current_file; ?>' width="150" height="120"></a>
            <?php
            if (isset($_SESSION['all'])):
                echo "<input class='checkbox' type=\"checkbox\" form=\"gallery\" name=\"$checkbox\" checked >";
            else:
                echo "<input class='checkbox' type=\"checkbox\" form=\"gallery\" name=\"$checkbox\">";
            endif;
            $count++;
        endif;
    endwhile;
    if (isset($_SESSION['all'])):
        unset($_SESSION['all']);
    endif;
    ?>
    <div >
        <hr>
        <button class="button" formmethod="post" name="delete" value="delete">Видалити вибрані файли</button>
        <button class="button" formmethod="post" name ="all" value="all">Вибрати усі файли</button>
        <button class="button" formmethod="post" name="reset" value="reset">Скинути вибір</button>
    </div>
</form>
</body>
</html>